### ISSUE TITLE
UI Command 

### ISSUE THREAD

**Issue by Ansh757** [CSC207-UofT/course-project-11-59pm#93]
Needs work even though the spacing is now fine and much better. Need to come up with some symbols to distinguish things and whatnot.

**Comment by KowanChan** [comment]
what does distinguish things mean?

**Comment by Ansh757** [comment]
Using symbols such as "=" or "-", labelling using headers so the user knows what is happening.

**Comment by armaan-mann** [comment]
Issue has been fixed
